#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8
# Been a long time

cp /etc/hosts ~/hosts.conf
echo "127.0.0.2		localhost" > ~/hosts.conf
echo "8.8.8.8		facebook.com" >> ~/hosts.conf
cp -f ~/hosts.conf /etc/hosts
